force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Experience__c/Car_Experience__c.object-meta.xml
<CustomObject>
    <label>Car Experience</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Experience__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipName>Car_Ratings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car_Experience__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <label>Experience</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/CarExperience.cls
public with sharing class CarExperience {
    @AuraEnabled
    public static List<Car_Experience__c> getExperiences(String carId){
        return [SELECT Id,
                    Name,
                    Experience__c,
                    LastModifiedDate,
                    CreatedDate,
                    CreatedBy.Name,
                    CreatedBy.SmallPhotoUrl,
                    CreatedBy.CompanyName
               FROM Car_Experience__c
               WHERE Car__c  = :carId
               ORDER BY CreatedDate DESC];
    }
}