force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Build_Year__c.field-meta.xml
<CustomField>
    <fullName>Build_Year__c</fullName>
    <label>Build Year</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Car_Type__c.field-meta.xml
<CustomField>
    <fullName>Car_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car Type</label>
    <referenceTo>Car_Type__c</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Per_Day_Rent__c.field-meta.xml
<CustomField>
    <fullName>Per_Day_Rent__c</fullName>
    <description>Per day rent of the car</description>
    <label>Per Day Rent</label>
    <precision>7</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car_Experience__c/Car_Experience__c.object-meta.xml
<CustomObject>
    <label>Car Experience</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Experience__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipName>Car_Ratings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car_Experience__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <label>Experience</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Car_Type__c/Car_Type__c.object-meta.xml
<CustomObject>
    <description>Property object to store different car type</description>
    <label>Car Type</label>
    <nameField>
        <label>Car Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/RentACarTestFactory.cls
public class RentACarTestFactory {

    public static List<Car_Type__c> createCarTypes(List<String> names){
        List<Car_Type__c> carTypes = new List<Car_Type__c>();
        for(String carTypeName : names){
            carTypes.add(new Car_Type__c(Name=carTypeName));
        }
        insert carTypes;
        return carTypes;
    }
    
    public static List<Contact> createContacts(List<String> names, Account acc){
        List<Contact> contacts = new List<Contact>();
        for(String contactName : names){
            contacts.add(new Contact(FirstName=contactName,
                                  LastName=contactName, AccountId=acc.id, Email='testcontact1@lightning.com'));
        }
        insert contacts;
        return contacts;
    }

    public static List<Account> createAccounts(List<String> names){
        List<Account> accounts = new List<Account>();
        for(String accName : names){
            accounts.add(new Account(Name=accName));
        }
        insert accounts;
        return accounts;
    }
    
    public static List<Car__c> createCars(List<Car_Type__c> cts, Contact con){
        List<Car__c> cars = new List<Car__c>();
        Integer i = 0;
        for(Car_Type__c ct : cts){
            //process record here
            cars.add(new Car__c(Contact__c=con.id, Car_Type__c=ct.id, 
                               Per_Day_Rent__c = 100+i,
                               Build_Year__c =2000+i,
                               Name='Car'+i));
            i++;
        }
        insert cars;
        return cars;
    }

    public static List<Car_Experience__c> createCarExperience(List<Car__c> cars){
        List<Car_Experience__c> carExperiences = new List<Car_Experience__c>();
        for(Car__c car : cars){
            //process record here
            carExperiences.add(new Car_Experience__c(Name='Test Experience', 
                                Experience__c='Test Detail Experience', 
                                Car__c = car.Id));
        }
        insert carExperiences;
        return carExperiences;
    }
    
}