force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Car_Type__c.field-meta.xml
<CustomField>
    <fullName>Car_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car Type</label>
    <referenceTo>Car_Type__c</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car_Experience__c/Car_Experience__c.object-meta.xml
<CustomObject>
    <label>Car Experience</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Experience__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipName>Car_Ratings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car_Type__c/Car_Type__c.object-meta.xml
<CustomObject>
    <description>Property object to store different car type</description>
    <label>Car Type</label>
    <nameField>
        <label>Car Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CarSearchResultControllerTest.cls
@isTest
public with sharing class CarSearchResultControllerTest {
    @TestSetup
    static void makeData(){
        List<Account> accounts = RentACarTestFactory.createAccounts(new List<String>{'Lightning Training'});
        List<Contact> contacts = RentACarTestFactory.createContacts(new List<String>{'Manish','Shivani','Ashish','Dushyant'}, accounts[0]);
        List<Car_Type__c> carTypes = RentACarTestFactory.createCarTypes(new List<String>{'Luxury','Sports','Van','Compact'});
        List<Car__c> cars = RentACarTestFactory.createCars(carTypes, contacts[0]);
        List<Car_Experience__c> carExperiences = RentACarTestFactory.createCarExperience(cars);
    }

    @isTest
    public static void testGetCarsWithCarTypeId(){
        Test.startTest();
        List<Car_Type__c> carTypes = [SELECT Id, Name FROM Car_Type__c];
        List<Car__c> cars = CarSearchResultController.getCars(carTypes[0].Id);
        Test.stopTest();
        System.assert(carTypes.size() == 4, 'Total 4 car type records should exist');
        System.assert(cars.size()==1, 'Only 1 car should exist per car type');
    }

    @isTest
    public static void testGetCarsWithoutCarTypeId(){
        Test.startTest();
        List<Car_Type__c> carTypes = [SELECT Id, Name FROM Car_Type__c];
        List<Car__c> cars = CarSearchResultController.getCars(null);
        Test.stopTest();
        System.assert(carTypes.size() == 4, 'Total 4 car type records should exist');
        System.assert(cars.size()==4, 'Total 4 car records should exist');
    }
}