force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Car_Type__c.field-meta.xml
<CustomField>
    <fullName>Car_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car Type</label>
    <referenceTo>Car_Type__c</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car_Type__c/Car_Type__c.object-meta.xml
<CustomObject>
    <description>Property object to store different car type</description>
    <label>Car Type</label>
    <nameField>
        <label>Car Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/DeleteData.cls
public class DeleteData {

    public static void deleteData(){
        List<Car__c> cars = [SELECT Id FROM Car__c];
        delete cars;
        
        List<Car_Type__c> carTypes = [SELECT Id FROM Car_Type__c];
        delete carTypes;
        
        List<String> emails = new List<String>();
        emails.add('testcontact1@lightning.com');
        emails.add('testcontact2@lightning.com');
        emails.add('testcontact3@lightning.com');
        emails.add('testcontact4@lightning.com');
        emails.add('testcontact5@lightning.com');
        emails.add('testcontact6@lightning.com');
        emails.add('testcontact7@lightning.com');
        emails.add('testcontact8@lightning.com');
        emails.add('testcontact9@lightning.com');
        emails.add('testcontact10@lightning.com');
        emails.add('testcontact11@lightning.com');
        emails.add('testcontact12@lightning.com');
        emails.add('testcontact13@lightning.com');
        emails.add('testcontact14@lightning.com');
        List<Contact> contacts = [SELECT Id FROM Contact WHERE Email IN:emails];
        delete contacts;
        
        List<Account> acc = [SELECT Id FROM Account WHERE Name='Lightning Training'];
        delete acc;
    }
}